import { readFile, writeFile } from 'fs/promises'
import { join } from 'path'
import { getAllSkills, type Skill } from '../skill/index'

export interface AgentsConfig {
  skills: Skill[]
  targetDir: string
}

export async function generateAgentsMd(config: AgentsConfig): Promise<void> {
  const { skills, targetDir } = config

  const content = generateAgentsContent(skills)

  const agentsPath = join(targetDir, 'agents.md')
  await writeFile(agentsPath, content, 'utf-8')
}

function generateAgentsContent(skills: Skill[]): string {
  const lines: string[] = [
    '# Agents Configuration',
    '',
    '> This file is auto-generated by skill-kit',
    '',
    '## Available Skills',
    ''
  ]

  for (const skill of skills) {
    lines.push(`### ${skill.name}`)
    lines.push('')

    if (skill.description) {
      lines.push(`> ${skill.description}`)
      lines.push('')
    }

    lines.push('**Files:**')
    lines.push(`- \`skills/${skill.name}/skill.md\` - Main skill file`)

    const refCount = skill.referenceCount
    if (refCount > 0) {
      lines.push(
        `- \`skills/${skill.name}/reference/\` - ${refCount} reference files`
      )
    }

    lines.push('')

    if (skill.frontmatter) {
      const { name, title, tags } = skill.frontmatter
      if (name || title || tags) {
        lines.push('**Metadata:**')
        if (name) lines.push(`- name: ${name}`)
        if (title) lines.push(`- title: ${title}`)
        if (tags) lines.push(`- tags: ${tags}`)
        lines.push('')
      }
    }
  }

  lines.push('---')
  lines.push('')
  lines.push('*Generated by skill-kit*')

  return lines.join('\n')
}

export async function appendToAgents(
  skill: Skill,
  targetDir: string
): Promise<void> {
  const agentsPath = join(targetDir, 'agents.md')

  let existingContent = ''
  try {
    existingContent = await readFile(agentsPath, 'utf-8')
  } catch {
    existingContent = ''
  }

  const newContent = generateAgentsContent([skill])

  const appendContent = '\n\n' + newContent

  await writeFile(agentsPath, existingContent + appendContent, 'utf-8')
}
